spring.application.name=chatbot
server.port=8000
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/spring-boot-realm-dev
spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4o-mini
