spring.application.name=chatbot
server.port=8000
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/spring-boot-realm-dev
spring.ai.openai.api-key=
spring.ai.openai.chat.options.model=gpt-4o-mini
